### PR TITLE
DR Homepage Banner: Added Banner Content

### PR DESCRIPTION
**Pull request by BenSpears1**
@timsb I have got as far as I can adding the code for a homepage banner however when trying to make changes in the dist/index.html code the changes don't update when trying to locally host. Inline styling is a substitute for working classes.

@JackHMRC We have put in some dummy copy. Please advise on content for the banner.

### CODE REVIEW

**Comment by timsb** [comment]
> @timsb I have got as far as I can adding the code for a homepage banner however when trying to make changes in the dist/index.html code the changes don't update when trying to locally host. Inline styling is a substitute for working classes.
> 
> @JackHMRC We have put in some dummy copy. Please advise on content for the banner.

@BenSpears1 I won't have time to take a look this week but will take a look at the start of next week.
It might be worth pulling this out into it's own Nunjucks component but I'll have a look next week.

**Comment by Jon-Rowe-HMRC** [comment]
Overall think this looks good. A few thought (sorry, I could have made some of these comments earlier)...

'save time and avoid designing things that already exist' > 'learn from the research and experience of other service teams and avoid repeating work that’s already been done'?
^ any thoughts on changing this to the GOV.UK wording or more similar? I slightly prefer it but it could be shortened to 'learn from the experience of other teams and avoid repeating work'

Can 'Use these design resources to make HMRC services consistent with GOV.UK. Employ GOV.UK and HMRC-specific patterns to save time and avoid designing things that already exist.' be styled like the GOV.UK version (currently serif font for me).

Suggest the box title 'HMRC Design Resources' is changed back to 'HMRC design patterns'. This pattern section is just a part of https://design.tax.service.gov.uk (which is the HMRC Design Resources).

'Find patterns and guidance developed specifically for HMRC users.' suggest removing ' users'. Some of our patterns are designed to override non-HMRC specific elements.

Please don't make any of the content suggestions above unless @JackHMRC agrees.

**Comment by Jon-Rowe-HMRC** [comment]
The header breaks onto two lines much earlier than it seems to need to.

Maybe change 'Design resources for HMRC' to 'HMRC design resources' across the board to help with this?

**Comment by timsb** [comment]
@Jon-Rowe-HMRC Apologies I pushed the commit up too early. I've added the correct font now to the description. I've also removed the br element in the banner title which means the word resources can hang on its own. I know we normally advise against having a single word on its own line. I can add an `&nbsp;` between the words 'Design' & 'Resources' to ensure they drop on a new line together when needed?

**Comment by JackHMRC** [comment]
> Overall think this looks good. A few thoughts (sorry, I could have made some of these comments earlier)...
> 
> 'save time and avoid designing things that already exist' > 'learn from the research and experience of other service teams and avoid repeating work that’s already been done'? ^ any thoughts on changing this to the GOV.UK wording or more similar? I slightly prefer it but it could be shortened to 'learn from the experience of other teams and avoid repeating work'
> 
> Can 'Use these design resources to make HMRC services consistent with GOV.UK. Employ GOV.UK and HMRC-specific patterns to save time and avoid designing things that already exist.' be styled like the GOV.UK version (currently serif font for me).
> 
> Suggest the box title 'HMRC Design Resources' is changed back to 'HMRC design patterns'. This pattern section is just a part of https://design.tax.service.gov.uk (which is the HMRC Design Resources).
> 
> 'Find patterns and guidance developed specifically for HMRC users.' suggest removing ' users'. Some of our patterns are designed to override non-HMRC specific elements.
> 
> Please don't make any of the content suggestions above unless @JackHMRC agrees.

Hey guys, I'm happy with Jon's suggestions. Looks good!

**Comment by Jon-Rowe-HMRC** [comment]
Now there is less text in the tiles, suggest they're shortened. Will help with the issue that we now have a longer page.

Using the bottom left tile as the template... Suggest changing so the distance from the ascenders on 'Government design principles' is used as the distance from the descender on 'government' too. That tile height is then used on all tiles.

**Pull request merged**
