### PR TITLE
New-freeport-maps-pattern

### PR DESCRIPTION
**Pull request by JackHMRC**

### CODE REVIEW

**Review by Jon-Rowe-HMRC — CHANGES_REQUESTED** [review]
In the first sentence the full stop should not be part of the link.

The link in the first sentence is dead (same when it's repeated lower down twice).

--

Avoid having h4s under h4s. This issue can usually be designed out. Maybe something like..
**Title**

For a single map:
The title should be 'Map of xxx [name] Freeport customs site.'

For multiple maps:
The title should be 'Maps of xxx [name] Freeport customs sites.'

--

'Use a different title to what you have used for the landing page.' Odd English? Maybe 'Use different titles for the landing page and HMTL attachment.'

In the last paragraph ' .D' > '. D'.

**Comment by JackHMRC** [comment]
Thanks John. I've added your edits. Do I need to ok the changes before I squash and merge?

**Review by Jon-Rowe-HMRC — COMMENTED** [review]
At the end of the second sentence, remove the space between the last word and full stop.

Under details there should not be h4s under h4s.

The full stop above 'Excluded nations' should be outside of the link.

At the end of the last link, remove the space between the last word and full stop.

**Comment by JackHMRC** [comment]
Added Jon's additional edits and updated 'What's new'.

**Review by Jon-Rowe-HMRC — DISMISSED** [review]
Approved to publish, but the Hs under Details are still irregular.

Be good to reword so there's no Hs within the Details section.

**Review by Jon-Rowe-HMRC — APPROVED** [review]

**Pull request merged**
