### PR TITLE
Timeout: not signed in

### PR DESCRIPTION
**Pull request by Jon-Rowe-HMRC**
Hi @timsb  and @ben-HMRC - this is incomplete but you can see the correction I'd like to make. I think further changes are required to the component for this amend to be fully made and I'm worried I might break something elsewhere by trying. Could one of you take it forward?

@JackHMRC could you check you're happy with the content change. Looks like this has always been incorrect.

### CODE REVIEW

**Comment by JackHMRC** [comment]
It looks as though we're removing the h1 "You’re about to be signed out". Is that right @Jon-Rowe-HMRC ?

**Comment by Jon-Rowe-HMRC** [comment]
That's my suggestion based on the guidance above the example. Not sure if it's needed for an overlay.

**Comment by timsb** [comment]
We set the modal with `aria-modal="true"` which hides the rest of the page to assistive tech which would mean there's no heading on the page at the point when the modal pops up so we'd need to add one. We also add an `aria-labelledby="hmrc-timeout-heading hmrc-timeout-message"`. The `hmrc-timeout-heading` being the h1 so it's needed for the purpose as well

**Comment by Jon-Rowe-HMRC** [comment]
@JackHMRC any improvements on...

h1: For your security
body: We will delete your answers in 2 minutes.

?

We'll also need to update the guidance above the example.

**Comment by JackHMRC** [comment]
@Jon-Rowe-HMRC 

Happy with this suggestion Jon. Let me know if you need anything else from me on this.

**Comment by Jon-Rowe-HMRC** [comment]
Thanks Jack. @timsb can you make the change as a whole?

**Comment by JackHMRC** [comment]
Sure no problem.

**Comment by timsb** [comment]
@JackHMRC I've updated the example but could you suggest updates to the wording above it now that it's split out.

We'll need some updated Welsh content for this example.

**Review by JackHMRC — APPROVED** [review]

**Pull request merged**
