### PR TITLE
Update design system to hmrc-frontend 4.1.0

### PR DESCRIPTION
**Pull request by tomshaw1**

### CODE REVIEW

**Review by timsb — CHANGES_REQUESTED** [review]
When I make this change locally I don't see that many changes to package-lock.json. What's your npm version?

**Review by klaudiarybicka — APPROVED** [review]

**Comment by tomshaw1** [comment]
@timsb My npm is version 8.3.2, tried `nvm use`, `npm install -g npm`, and then an `npm install` as that worked when this happened previously but no changes this time.

**Comment by timsb** [comment]
> @timsb My npm is version 8.3.2, tried `nvm use`, `npm install -g npm`, and then an `npm install` as that worked when this happened previously but no changes this time.

@tomshaw1 Could you try `npm install -g npm@6`

**Comment by tomshaw1** [comment]
> > @timsb My npm is version 8.3.2, tried `nvm use`, `npm install -g npm`, and then an `npm install` as that worked when this happened previously but no changes this time.
> 
> @tomshaw1 Could you try `npm install -g npm@6`

@timsb , tried this now, it made no changes to the file unfortunately

**Comment by tomshaw1** [comment]
Closed to do this change on a different branch

**Pull request closed without merging**
