### PR TITLE
File upload

### PR DESCRIPTION
**Pull request by Jon-Rowe-HMRC**
Tim... besides the updates I've just made, these are my suggested further changes to the example code:

'You have added 2 receipts' > 'Upload receipts'
'file upload' and '33% uploaded' in their own column
'Change | ' removed

Could you make changes to the preview ahead of our call tomorrow so it's clear what we want?

We might need further guidance on error messages for edge cases. Like what happens if a file upload is still in progress, the user selects no and continue.

### CODE REVIEW

**Comment by timsb** [comment]
@Jon-Rowe-HMRC the add to list pattern doesn't currently let us add a third column like `.govuk-summary-list__value` as the govuk-summary-list enables us to. I could swap out the add to list and manually build the govuk-summary-list and form items but that removes a lot of the automatic stuff that add-to-list does.

I have been able to make the first column longer (50%) so I don't know if you'd be ok with us using it as plain text with a longer column?

**Comment by Jon-Rowe-HMRC** [comment]
@timsb having a longer first column instead of a second one might work

**Comment by timsb** [comment]
@Jon-Rowe-HMRC Ahead of the meeting this afternoon I've uploaded an HTML (rather than Nunjucks) version of what we want. Let me know if those changes aren't correct.

**Comment by Jon-Rowe-HMRC** [comment]
@timsb looks good for the purpose of the meet.

I had meant for 'Upload receipts' to replace the h1 as 'You have added X receipts' might lead users to think their uploads are complete when they might be in progress

**Pull request closed without merging**
